name: 👷 publish image
permissions: write-all

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**

jobs:
  build:
    name: publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/${{ github.repository }}:latest-build-cache
          cache-to: ghcr.io/${{ github.repository }}:latest-build-cache
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest

      - name: Summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          ### Pushed images
          * ghcr.io/${{ github.repository }}:${{ github.sha }}
          * ghcr.io/${{ github.repository }}:latest
          EOF
