name: 👷 test image
permissions: write-all

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: test image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Sanitize branch name
        id: sanitize_branch
        run: |
          SANITIZED_BRANCH=$(echo -n "${{ github.ref_name }}" | tr '/' '-' | tr -c '[:alnum:]-' '-')
          echo sanitized_branch=$SANITIZED_BRANCH >> $GITHUB_OUTPUT

      - name: Build image for tests
        uses: docker/build-push-action@v6
        with:
          load: true
          target: tests
          cache-from: ghcr.io/${{ github.repository }}:latest-build-cache
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }} 

      - name: run tests
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }} 
      
      - name: lint check
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }}  ruff check

      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/${{ github.repository }}:latest-build-cache
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }}

      - name: Summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          ### Pushed images
          * ghcr.io/${{ github.repository }}:${{ steps.sanitize_branch.outputs.sanitized_branch }}
          EOF
